all:
	$(MAKE) -f Makefile.1xx install
	$(MAKE) -f Makefile.hge install
	$(MAKE) -f Makefile.input install
	$(MAKE) -f Makefile.box2d install

1xx:
	$(MAKE) -f Makefile.1xx install
	$(MAKE) -f Makefile.hge install
	$(MAKE) -f Makefile.input install
	$(MAKE) -f Makefile.box2d install

3xx:
	$(MAKE) -f Makefile.3xx install
	$(MAKE) -f Makefile.hge install
	$(MAKE) -f Makefile.input install
	$(MAKE) -f Makefile.box2d install

clean:
	$(MAKE) -f Makefile.1xx clean
	$(MAKE) -f Makefile.3xx clean
	$(MAKE) -f Makefile.hge clean
	$(MAKE) -f Makefile.input clean
	$(MAKE) -f Makefile.box2d clean
