all:
	$(MAKE) -f Makefile.1xx install
	$(MAKE) -f Makefile.hge install

150:
	$(MAKE) -f Makefile.1xx install
	$(MAKE) -f Makefile.hge install

3xx:
	$(MAKE) -f Makefile.3xx install
	$(MAKE) -f Makefile.hge install

clean:
	$(MAKE) -f Makefile.1xx clean
	$(MAKE) -f Makefile.3xx clean
	$(MAKE) -f Makefile.hge clean
